---
- name: Install samba
  apt:
    name: samba
    state: present

- name: Create base smb share dir
  file:
    path: "{{ smb_base_dir }}"
    state: directory
    recurse: yes

- name: Set base smb share dir permissions
  file:
    path: "{{ smb_base_dir }}"
    state: directory
    mode: 0755

- name: Create smb users
  include_tasks: create-smb-user.yml
  loop: "{{ smb_users }}"
  loop_control:
    loop_var: user

- name: Create smb shares
  file:
    path: "{{ share.dir }}"
    state: directory
    owner: "{{ share.owner  }}"
    group: "{{ share.group  }}"
    mode: 0770
    recurse: yes
  loop: "{{ smb_shares }}"
  loop_control:
    loop_var: share

- name: Template smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: 0644

- name: Restart and enable smbd service
  systemd:
    name: smbd
    enabled: yes
    state: restarted
